Develop
mate-academy/js_employees_table_DOM pull request #114
Opened 2021-12-21 19:43 UTC by voronvasia

https://voronvasia.github.io/js_employees_table_DOM/

2021-12-22 12:24 UTC, vkryvytskyy requested changes
Нужно пофиксить добавление записей и редактирование

2021-12-22 12:24 UTC, vkryvytskyy commented on README.md
> +   - [DEMO LINK](https://voronvasia.github.io/js_employees_table_DOM/)
https://user-images.githubusercontent.com/38065883/147092013-251b21ff-7362-410e-93bf-199beb61c09e.mov

Видно как ошибки накладываются друг на друга, перед добавлением нового сообщения - удаляй старое

2021-12-22 12:24 UTC, vkryvytskyy commented on README.md
> +   - [DEMO LINK](https://voronvasia.github.io/js_employees_table_DOM/)
![image](https://user-images.githubusercontent.com/38065883/147092087-6ff02bc4-01ab-4ba7-a570-b83c34e5c3d8.png)
У меня получилось добавить запись в таблицу без зарплаты и с возрастом в видк букв

2021-12-22 12:24 UTC, vkryvytskyy commented on README.md
> +   - [DEMO LINK](https://voronvasia.github.io/js_employees_table_DOM/)
![image](https://user-images.githubusercontent.com/38065883/147092167-e63839c7-82dc-4bcd-879c-faac13a5dd46.png)
При редактировании офиса должен появляться селект, а не просто инпут, чтобы мы могли вставить только нужное значение туда

2021-12-22 12:24 UTC, vkryvytskyy commented on README.md
> +   - [DEMO LINK](https://voronvasia.github.io/js_employees_table_DOM/)
![image](https://user-images.githubusercontent.com/38065883/147092274-73e00718-da0f-4e73-b04e-3d07f0cedfdc.png)
Можно отредактировать строку так, что в ней все значения будут пустыми

2021-12-22 12:24 UTC, vkryvytskyy commented on README.md
> +   - [DEMO LINK](https://voronvasia.github.io/js_employees_table_DOM/)
![image](https://user-images.githubusercontent.com/38065883/147092339-169b97e8-c0e4-4bb3-bff4-3851c5ff8ceb.png)
Или сделать вот такую зарплату

2021-12-24 12:07 UTC, varseniuk requested changes
Зараз можна ввести від'ємний вік і зарплату
<img width="646" alt="Снимок экрана 2021-12-24 в 14 04 30" src="https://user-images.githubusercontent.com/66570142/147351305-0bf6fe71-8897-468f-89d3-4838d4b0f682.png">

При спробі редагувати місто, зразу ж встановлюється Tokyo, навіть якщо я ще не встиг нічого вибрати. Тобто, якби я передумав міняти значення вже після кліку, то Токіо встановилось би все одно. Потрібно, щоб значення мінялось тільки тоді, коли я його міняю

https://user-images.githubusercontent.com/66570142/147351363-fdd60c7a-de05-467e-8f0b-503b22186fec.mov

Також, було б добре конкретно вказувати, яку інформацію я ввожу некоректно. Зараз є тільки одне повідомлення про помилку для всіх випадкуів. І, скажімо, коли я введу некоректний вік, я не буду знати, які там ліміти. Помилка буде просто про невалідні введені дані

2021-12-28 12:50 UTC, aliceblunt8 approved these changes
good job! єдине коли буде час і натхнення підфікси розташування месседжу, бо зараз накладається на форму
<img width="545" alt="Screenshot 2021-12-28 at 14 49 45" src="https://user-images.githubusercontent.com/57598825/147567919-7816ee29-3ae1-4bee-ae19-52f69e632449.png">

2023-12-09 20:00 UTC, closed without merging