done
mate-academy/js_employees_table_DOM pull request #19
Opened 2020-10-15 16:55 UTC by aionova

- [DEMO LINK](https://aionova.github.io/js_employees_table_DOM/)

2020-10-16 07:39 UTC, yazheviks approved these changes
Пушкаракета)

2020-10-16 08:06 UTC, danheim requested changes

2020-10-16 08:06 UTC, danheim commented on src/scripts/main.js
> +    }
у тебя этот код повторяется в else

2020-10-16 08:28 UTC, aionova commented on src/scripts/main.js
> +    }
да, но это 2 разных sort создается, и соответственно, это не одни и те же a и b. я думала, как их в переменные записать, сократить, но не придумала..

2020-10-20 15:21 UTC, aliceblunt8 requested changes
Good job! Below are some things that can be enhanced ;)

- reset form after submit (now after adding a new employee I can click again and the same person will be added to the form)
- when double-clicked the form changes its width
- newly added employees couldn't be sorted
- for the code to look neater and be more understandable for others try to wrap every action and everything related to it in a separate function (like createForm, addTableSorting, addTableEditing, etc)

2023-09-27 09:17 UTC, closed without merging