all done
mate-academy/js_employees_table_DOM pull request #200
Opened 2022-09-06 07:49 UTC by Yevhen-Pavlovskyi

https://yevhen-pavlovskyi.github.io/js_employees_table_DOM/

2022-09-08 17:21 UTC, SanyaBratashchuk requested changes
1. зміг створити без salary
![image](https://user-images.githubusercontent.com/97547824/189184400-2b59123e-92f7-4062-8049-85127e5b65a1.png)
2. Також трохи не співпадає валідація коли редагуєш і коли створюєш доприкладу при створенні я зміг ввести CEO в posiiton, а редагувати на CEO вже не можу

2022-09-17 14:28 UTC, ivanchuk-yurii requested changes
try to fix changing of cell width when you click on it and input appears
sorry for extra comments((

2022-09-17 14:28 UTC, ivanchuk-yurii commented on src/scripts/main.js
> +            td.textContent = `${tag.value}`;
will be ok without conversion to string

2022-09-17 14:28 UTC, ivanchuk-yurii commented on src/scripts/main.js
> +            td.textContent = `$${parseInt(tag.value).toLocaleString('en-EN')}`;
you can also add `{style:"currency", currency:"USD"}` option for `toLocaleString`

2022-09-17 14:28 UTC, ivanchuk-yurii commented on src/scripts/main.js
> +            td.textContent = `$${parseInt(tag.value).toLocaleString('en-EN')}`;
https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_tolocalestring_num_options3

2022-09-17 14:28 UTC, ivanchuk-yurii commented on src/scripts/main.js
> +          'error');
closing bracket `)` should be on the same line as opening `(`, fix in other places

2022-09-17 14:28 UTC, ivanchuk-yurii commented on src/scripts/main.js
> +      input.value = tdText;
you should convert value for salary from string to number in right way, bc now it's not inserting previous value in the input

2022-09-17 14:28 UTC, ivanchuk-yurii commented on src/scripts/main.js
> +        ></label>
move text and tag on the new lines

2022-09-17 14:28 UTC, ivanchuk-yurii commented on src/scripts/main.js
> +    toggle *= -1;
if you click on another header, toggle won't be cleared

2022-09-17 14:28 UTC, ivanchuk-yurii commented on src/scripts/main.js
> +            .innerHTML.split('$').join('').split(',').join('')
use `replace`, move in helper function

2022-09-22 08:36 UTC, closed without merging