solution
mate-academy/js_employees_table_DOM pull request #21
Opened 2020-10-19 12:45 UTC by andlap24

[DEMO LINK](https://andlap24.github.io/js_employees_table_DOM/)

2020-10-19 15:02 UTC, achervona approved these changes

2020-10-19 15:02 UTC, achervona commented on src/scripts/main.js
> +const tBody = table.children[1];
лучше наверно tBody объявить где-то в начале файла и использовать только его, а то у тебя до этого используется table.tBodies[0] и это запутывает немного

2020-10-19 15:35 UTC, andlap24 commented on src/scripts/main.js
> +const tBody = table.children[1];
да, верно. Запутанно.

2020-10-20 15:34 UTC, aliceblunt8 requested changes
Good job! Here're some comments for further improvements
- reset form after submit (now after adding a new employee I can click again and the same person will be added to the form)
- for the code to look neater and be more understandable try to wrap every action and everything related to it in a separate function (like createForm, addTableSorting, etc)

2026-02-15 13:26 UTC, closed without merging