done1
mate-academy/js_employees_table_DOM pull request #255
Opened 2022-12-05 18:42 UTC by panianchuk

https://panianchuk.github.io/js_employees_table_DOM/

2022-12-06 17:58 UTC, loralevitska requested changes
Looks great) Let's improve

1. It would be good to be in the plus on salary. Limit negative values
![image](https://user-images.githubusercontent.com/70009205/205985732-faa4b05b-188f-4085-8c87-6d54e43b9dd2.png)

2022-12-06 17:58 UTC, loralevitska commented on src/scripts/main.js
> +  return +res;
```suggestion
  return Number(res);
```

2022-12-06 17:58 UTC, loralevitska commented on src/scripts/main.js
> +  if (key === 'age' && (+value < 18 || +value > 90)) {
It's better to set the min and max attributes for the input, this way you will avoid unnecessary checks and it will be clearer to the user

2022-12-08 09:12 UTC, stanislav-topikha approved these changes
GJ 👍🏻

2023-12-29 10:46 UTC, closed without merging