Solution
mate-academy/js_employees_table_DOM pull request #266
Opened 2022-12-13 14:08 UTC by Ivanenko1402

[DEMO LINK](https://Ivanenko1402.github.io/js_employees_table_DOM/)

2022-12-14 13:54 UTC, Virass requested changes
Нові персонажі в таблиці виділені жирним. Вони не сортуються з іншими, їм не можна змінити зарплатню, для інших немає валідації при зміні даних. У вік я можу записати строки. Коли обираю ново створеноко персонажа і намагаюсь його редагувати, в мене це не виходить і для інших потім також.
![image](https://user-images.githubusercontent.com/24947782/207613094-ff8fb10b-3d47-40d9-8737-142e1b99020b.png)

2022-12-15 15:26 UTC, loralevitska requested changes
almost done)
1. I can add negative salary
![image](https://user-images.githubusercontent.com/70009205/207898112-f2ecdecf-5c08-45e6-95a1-c459388c0765.png)
2. The edited value is not sorted correctly
![image](https://user-images.githubusercontent.com/70009205/207898780-9dbc525b-3b17-418f-8015-745826b369b8.png)

2022-12-15 15:26 UTC, loralevitska commented on src/scripts/main.js
> +          : +x.replaceAll(/\W/g, '') - +y.replaceAll(/\W/g, '');
DRY
move regexp to constant

2022-12-15 15:26 UTC, loralevitska commented on src/scripts/main.js
> +            );
Avoid code duplicate
Imagine that now you hire people under the age of 50... How many times in the code will you have to change this number?

Move all duplicates to helper function or variables

2022-12-16 16:36 UTC, loralevitska requested changes
almost done)
If your have some problems fill free to ask in fe_chat

2022-12-16 16:36 UTC, loralevitska commented on src/scripts/main.js
> +      'age must be more than 18 and less than 90',
`'age must be more than 18 and less than 90'` repeated twice in the code: move this to constant.

2022-12-18 12:17 UTC, SanyaBratashchuk approved these changes

2026-03-02 13:40 UTC, closed without merging