Solution
mate-academy/js_employees_table_DOM pull request #292
Opened 2023-01-15 19:49 UTC by tarasavage

[DEMO LINK](https://tarasavage.github.io/js_employees_table_DOM/)

2023-01-16 20:14 UTC, witflash requested changes
Good job!
Check my comments, please.

2023-01-16 20:14 UTC, witflash commented on src/scripts/main.js
> +  switch (selectedCell.cellIndex) {
You could use an `if / else` block instead of `switch / case`. You don't need to use it for two cases.

2023-01-16 20:14 UTC, witflash commented on src/scripts/main.js
> +    : 0;
```
if (indexTitle !== currentIndex) {
  counter = 0;
}
```

2023-01-16 20:14 UTC, witflash commented on src/scripts/main.js
> +    }
It's a very complex block for me. 
Could you use only one approach (`switch/case` or `if/else`)?

2023-01-18 17:38 UTC, Viktor-Kost approved these changes
Nice!

2023-02-01 23:18 UTC, closed without merging