Sorting in two direction
mate-academy/js_employees_table_DOM pull request #319
Opened 2023-02-20 07:48 UTC by NazariiAlieksieiev

2023-02-20 13:19 UTC, IvanFesenko requested changes
Write a script to add a form to the document. Form allows users to add new employees to the spreadsheet. 
Where is form?
![2023-02-20_15h18_19](https://user-images.githubusercontent.com/61904995/220119720-06f838ce-b5c4-4899-861d-755ca1b89406.png)

2023-02-20 13:21 UTC, NazariiAlieksieiev commented
> Write a script to add a form to the document. Form allows users to add new employees to the spreadsheet. 
> 
> Where is form?
> 
> ![2023-02-20_15h18_19](https://user-images.githubusercontent.com/61904995/220119720-06f838ce-b5c4-4899-861d-755ca1b89406.png)
> 
> 

Forgot run deploy

2023-02-20 15:11 UTC, mykhalenych requested changes
missed requirement
1. All fields are required.
2. Click on Save to table should run validation for form inputs. If data is valid, add a new employee to the table.
3. If Name value has less than 4 letters, show error notification.
4 .If Age value is less than 18 or more than 90 show error notification.

And I don't see notification, check it too

2023-02-26 08:33 UTC, VitaliyBondarenko1982 approved these changes

2024-07-27 11:11 UTC, closed without merging