solution
mate-academy/js_employees_table_DOM pull request #420
Opened 2023-05-29 14:21 UTC by LiliiaDanylenko

- [DEMO LINK](https://LiliiaDanylenko.github.io/js_employees_table_DOM/)

2023-05-29 15:29 UTC, slavanosatskyi requested changes
test

2023-05-30 06:11 UTC, vlad-demchuk requested changes
test

2023-05-30 07:18 UTC, vlad-demchuk approved these changes

2023-05-30 07:24 UTC, vlad-demchuk requested changes
test

2023-05-30 12:17 UTC, closed without merging

2023-05-30 14:05 UTC, Bohdan-Maksymiuk approved these changes

2023-05-31 06:24 UTC, vlad-demchuk requested changes
GJ

I can change data in table to invalid one
<img width="721" alt="image" src="https://github.com/mate-academy/js_employees_table_DOM/assets/102411130/1dfc42d1-2f86-49ab-bc90-304cbee3a74f">

2023-05-31 06:24 UTC, vlad-demchuk commented on src/scripts/main.js
> +let temp = null;
use more descriptive variable names

2023-05-31 06:24 UTC, vlad-demchuk commented on src/scripts/main.js
> +      ${offices.map(office => `<option>${office}</option>`).join('')}
you do it twice
`${offices.map(office => `<option>${office}</option>`).join('')}`

you can create a separate function to to it

2023-05-31 06:24 UTC, vlad-demchuk commented on src/scripts/main.js
> +// for test
remove comments

2023-06-01 07:36 UTC, vlad-demchuk approved these changes