solution
mate-academy/js_employees_table_DOM pull request #433
Opened 2023-06-10 20:17 UTC by Vo7kov

https://vo7kov.github.io/js_employees_table_DOM/

2023-06-11 10:23 UTC, TarasHoliuk commented
1. Use the image exported from the mobile version in Figma (instead of using huge image and cut it):
![image](https://github.com/mate-academy/js_employees_table_DOM/assets/86923089/7b33b2cd-50ca-4aeb-ae2d-0fab237629ec)
App: 
![image](https://github.com/mate-academy/js_employees_table_DOM/assets/86923089/30ddfc3b-0cee-43de-9067-5b798bc438d1)

2. This image shouldn't contain this label:
![image](https://github.com/mate-academy/js_employees_table_DOM/assets/86923089/f5df8475-4aac-4b91-868d-3f9721bb06ce)

![image](https://github.com/mate-academy/js_employees_table_DOM/assets/86923089/6b20ebdb-fd54-4c84-943a-a59490da3c10)

2023-06-11 10:24 UTC, TarasHoliuk requested changes
You did an amazing job :+1: 
Only a few minor things might be fixed (check comments)

2023-06-11 10:30 UTC, TarasHoliuk commented
Would be nice to add `select` input on the `Office` column edit:
![image](https://github.com/mate-academy/js_employees_table_DOM/assets/86923089/e2b93090-0c24-4533-90c8-64f98098df14)

Implement this part:
![image](https://github.com/mate-academy/js_employees_table_DOM/assets/86923089/e8a4cdc9-9abf-4704-a880-8c2855750fcd)

Do not forget to trim values (when editing and when adding a new row) to avoid adding empty (with spaces only) values

2023-06-11 10:40 UTC, TarasHoliuk requested changes

2023-06-11 10:40 UTC, TarasHoliuk commented on src/scripts/main.js
> +      if (index === 0 || index === 1 || index === 2) {
do not use magic numbers, save indices to meaningful (with column name) names

2023-06-11 10:40 UTC, TarasHoliuk commented on src/scripts/main.js
> +    if (isClickedFirst) {
you're duplicating a big part of your code
try to overwrite it a bit (e.g. handle sort order in every separate case)

2023-06-11 10:40 UTC, TarasHoliuk commented on src/scripts/main.js
> +      if (index === 0 || index === 1 || index === 2) {
use `switch`
hint: you can join a few cases, for example:
```
case 0:
case 1:
case 2:
  sortedTrsBody = // rest your code
```

2023-06-12 16:57 UTC, etojeDenys approved these changes

2025-07-07 14:13 UTC, closed without merging