Develop
mate-academy/js_employees_table_DOM pull request #646
Opened 2024-09-19 18:15 UTC by RomanMartseniuk

- [DEMO LINK](https://romanmartseniuk.github.io/js_employees_table_DOM/)

2024-09-19 18:22 UTC, etojeDenys requested changes
age and salary should also be required
<img width="753" alt="image" src="https://github.com/user-attachments/assets/b71ac39b-ee88-4b1a-979f-cacb7e432387">

2. you need to validate edited inputs too
<img width="791" alt="image" src="https://github.com/user-attachments/assets/c966faa9-db44-4ca1-966f-05c8ad057129">

3. it should be inputs with type="number"
<img width="323" alt="image" src="https://github.com/user-attachments/assets/46474bf6-95a0-4b41-b2c8-a9c26f519f12">

2024-09-22 09:32 UTC, anastasiiavorobiova requested changes
Great work! Consider removing the commented code block.

2024-09-22 09:32 UTC, anastasiiavorobiova commented on src/scripts/main.js
> +  // });
```suggestion

```

2024-09-22 09:33 UTC, anastasiiavorobiova requested changes
Great work! Consider removing the commented code block.

2024-09-22 09:59 UTC, SanyaBratashchuk approved these changes

2025-12-26 22:15 UTC, closed without merging