solution
mate-academy/js_employees_table_DOM pull request #89
Opened 2021-08-23 16:24 UTC by Bohdan996

- [DEMO LINK](Bohdan996.github.io/js_employees_table_DOM/)

После добавления нового работника, список его не сортирует. Помогите разобраться в чём ошибка.

2021-08-23 19:24 UTC, vpolets requested changes

2021-08-23 19:24 UTC, vpolets commented on src/scripts/main.js
> +    setTimeout(() => document.querySelector('.error').remove(), 2000);
створи функцію create Notification і її використовуй

2021-08-23 19:24 UTC, vpolets commented on src/scripts/main.js
> +const array = [...tbody.rows];
Якщо правильно зрозумів ти зробив копію, а потім сортуєш саме цей array, а у ньому немає нових співробників, для сортування варто витягувати з DOM актуальний масив рядків

2021-08-23 19:24 UTC, vpolets commented on src/scripts/main.js
> +
створи функцію createEmployeeForm і в ній ховай всю логіку, не треба загальним полотном все змішувати діли код на логічні блоки. Чи більше окремих функцій (інструкцій) ти напишеш з ясними назвами, тим легше буде читати твій код

2021-08-23 19:24 UTC, vpolets commented on src/scripts/main.js
> +    const result = array.sort((a, b) => {
ось ти сортуєш той же масив

2021-08-23 19:24 UTC, vpolets commented on src/scripts/main.js
> +        <td>${salaryString(document.querySelector('#salary').value)}</td>
а тут ти додав новий елемент, але array про це нічого не знає

2021-08-24 14:52 UTC, Bohdan996 commented on src/scripts/main.js
> +        <td>${salaryString(document.querySelector('#salary').value)}</td>
Дякую, здаєтсься розібрався.

2021-09-06 09:01 UTC, mykola-yarchuk approved these changes

2022-11-28 07:15 UTC, closed without merging